import = [
    "C:/Users/sanil/AppData/Roaming/alacritty/catppuccin-mocha.toml"
]

# for windows
[shell]
args = ["--cd ~"]
program = 'C:\Windows\System32\wsl.exe'

# for linux
# [shell]
# program = '/usr/bin/zsh'

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 60 }
dynamic_padding = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Italic" }