# for windows
# import = [
#     "C:\\Users\\sanil\\AppData\\Roaming\\alacritty\\catppuccin_mocha.toml",
# ]
# [shell]
# args = ["--cd ~"]
# program = 'C:\Windows\System32\wsl.exe'

# for linux
general.import = ["/home/sanil/.config/alacritty/catppuccin_mocha.toml"]

[terminal.shell]
program = '/usr/bin/zsh'

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 160, lines = 60 }
dynamic_padding = true

[font]
normal = { family = "Fira Code", style = "Regular" }
bold = { family = "Fira Code", style = "Bold" }
italic = { family = "Fira Code", style = "Regular" }
bold_italic = { family = "Fira Code", style = "Bold" }

# for windows
# normal = { family = "FiraCode Nerd Font", style = "Retina" }
# bold = { family = "FiraCode Nerd Font", style = "Bold" }
# italic = { family = "FiraCode Nerd Font", style = "Italic" }
# bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
